<a href="https://colab.research.google.com/github/DivyanshKs/Coursera-test/blob/master/NumPy%20Practices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
l = list(range(1,11))
print("List : ",l)
arr = np.array(l)
print("Array : ",arr)

List :  [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
Array :  [ 1  2  3  4  5  6  7  8  9 10]


In [4]:
type(arr)
arr.dtype

dtype('int64')

In [6]:
l2 = [1,2.0,'Three', True]
arr2 = np.array(l2)
print("Array 2 : ",arr2)

Array 2 :  ['1' '2.0' 'Three' 'True']


In [7]:
type(arr2)
for i in arr2:
  print(type(i))

arr2.dtype

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


dtype('<U32')

In [8]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
a = np.arange(-10,0,2)
print(a)
a=a*2
print(a)
print(a.sum())
print(a.size)
print(np.abs(a))
b = np.array([1.2, 2.3, 3.4, 4.6, 5.0])
print(np.ceil(b))
print(np.floor(b))
print(np.around(b,decimals=0))

[-10  -8  -6  -4  -2]
[-20 -16 -12  -8  -4]
-60
5
[20 16 12  8  4]
[2. 3. 4. 5. 5.]
[1. 2. 3. 4. 5.]
[1. 2. 3. 5. 5.]


In [10]:
c = np.arange(5,15)
c[2:8]=-2
c

array([ 5,  6, -2, -2, -2, -2, -2, -2, 13, 14])

In [11]:
c[2:8] = [1, 2, 3, 4, 5, 6]
c

array([ 5,  6,  1,  2,  3,  4,  5,  6, 13, 14])

In [12]:
d = c[2:8].copy()
print("d ",d)
c[2] = 100
print("c ",c)
print("d ",d)
d[4] = 100
print("c ",c)
print("d ",d)

d  [1 2 3 4 5 6]
c  [  5   6 100   2   3   4   5   6  13  14]
d  [1 2 3 4 5 6]
c  [  5   6 100   2   3   4   5   6  13  14]
d  [  1   2   3   4 100   6]


In [26]:
arr3 = np.arange(1,13)
arr4 = arr3.reshape(3,4)
print("Array 3 ",arr3)
print(arr4)
arr4 = arr4+(4*5)
print(arr4)
arr4 = arr4.reshape(2,1,6)
arr4

Array 3  [ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


array([[[21, 22, 23, 24, 25, 26]],

       [[27, 28, 29, 30, 31, 32]]])

In [27]:
arr4[0]

array([[21, 22, 23, 24, 25, 26]])

In [35]:
print(arr4[0][0][5])
arr4[1,0,5]

26


32

In [39]:
arr4[0,0,::2]

array([21, 23, 25])

In [46]:
arr4 = arr4.reshape(2,2,3)
print(arr4)
print(arr4[:2,:1,1:2])
print(arr4.T)
arr4[:,1:2,:] = arr4[:,1:2,:]-20
print(arr4)

[[[21 22 23]
  [24 25 26]]

 [[27 28 29]
  [30 31 32]]]
[[[22]]

 [[28]]]
[[[21 27]
  [24 30]]

 [[22 28]
  [25 31]]

 [[23 29]
  [26 32]]]
[[[21 22 23]
  [ 4  5  6]]

 [[27 28 29]
  [10 11 12]]]


In [47]:
arr4.sum(axis=0)

array([[48, 50, 52],
       [14, 16, 18]])

In [48]:
arr4.sum(axis=1)

array([[25, 27, 29],
       [37, 39, 41]])

In [49]:
arr4.cumsum()

array([ 21,  43,  66,  70,  75,  81, 108, 136, 165, 175, 186, 198])

In [51]:
arr4.prod()

36901564761600